global using Microsoft.Extensions.DependencyInjection;
global using TECSearchApp.Logic.Data;
global using TECSearchApp.Logic.Enums;
global using TECSearchApp.Logic.Interfaces;
global using TECSearchApp.Logic.Model;
global using TECSearchApp.Logic.Services;
global using TECSearchApp.UI.AppFlow;
global using TECSearchApp.UI.Interfaces;
global using TECSearchApp.UI.Views;
